/**
 * Convert a snarkjs verification_key.json into Rust constants for the on-chain
 * verifier (groth16-solana byte layout: big-endian, G2 coordinates as c1||c0,
 * matching the Ethereum precompile convention the crate follows).
 *
 *   node vk-to-rust.js artifacts/verification_key.dev.json > ../programs/zsol/src/vk.rs
 */
const fs = require('fs');

const path = process.argv[2];
if (!path) { console.error('usage: node vk-to-rust.js <verification_key.json>'); process.exit(1); }
const vk = JSON.parse(fs.readFileSync(path, 'utf8'));

if (vk.protocol !== 'groth16' || vk.curve !== 'bn128') {
  console.error('expected a groth16 / bn128 key'); process.exit(1);
}

// 32-byte big-endian encoding of a decimal field element.
function be32(dec) {
  let n = BigInt(dec);
  const out = new Array(32).fill(0);
  for (let i = 31; i >= 0; i--) { out[i] = Number(n & 0xffn); n >>= 8n; }
  return out;
}
const g1 = (p) => [...be32(p[0]), ...be32(p[1])];                       // x || y
const g2 = (p) => [...be32(p[0][1]), ...be32(p[0][0]), ...be32(p[1][1]), ...be32(p[1][0])]; // x.c1||x.c0||y.c1||y.c0

const fmt = (arr, per = 16) => {
  const lines = [];
  for (let i = 0; i < arr.length; i += per) {
    lines.push('    ' + arr.slice(i, i + per).map((b) => b.toString().padStart(3)).join(', ') + ',');
  }
  return lines.join('\n');
};

const ic = vk.IC.map(g1);

let out = '';
out += '//! Groth16 verifying key — GENERATED by circuits/vk-to-rust.js. Do not edit.\n';
out += '//!\n';
out += `//! Source: ${path.split('/').pop()}  (nPublic = ${vk.nPublic})\n`;
out += '//!\n';
out += '//! This is the DEV key from a local, throwaway trusted setup. A mainnet\n';
out += '//! deployment must regenerate this file from a real multi-party ceremony.\n';
out += '\n';
out += 'use groth16_solana::groth16::Groth16Verifyingkey;\n\n';
out += `pub const NR_PUBLIC_INPUTS: usize = ${vk.nPublic};\n\n`;
out += 'pub const VERIFYING_KEY: Groth16Verifyingkey = Groth16Verifyingkey {\n';
out += `    nr_pubinputs: ${vk.nPublic},\n\n`;
out += '    vk_alpha_g1: [\n' + fmt(g1(vk.vk_alpha_1)) + '\n    ],\n\n';
out += '    vk_beta_g2: [\n' + fmt(g2(vk.vk_beta_2)) + '\n    ],\n\n';
out += '    vk_gamme_g2: [\n' + fmt(g2(vk.vk_gamma_2)) + '\n    ],\n\n';
out += '    vk_delta_g2: [\n' + fmt(g2(vk.vk_delta_2)) + '\n    ],\n\n';
out += '    vk_ic: &[\n';
for (const p of ic) out += '        [\n' + fmt(p).replace(/^ {4}/gm, '            ') + '\n        ],\n';
out += '    ],\n';
out += '};\n';

process.stdout.write(out);
