/**
 * Caller nicknames for every ball, 1-75.
 *
 * The old hall calls, trimmed to the 75-ball range and with a few swapped for
 * something that lands better on-chain. Shown above the ball as it drops.
 */
const CALLS: Record<number, string> = {
  1: 'Kelly’s eye',
  2: 'One little duck',
  3: 'Cup of tea',
  4: 'Knock at the door',
  5: 'Man alive',
  6: 'Half a dozen',
  7: 'Lucky seven',
  8: 'Garden gate',
  9: 'Doctor’s orders',
  10: 'Uncle Ben',
  11: 'Legs eleven',
  12: 'One dozen',
  13: 'Unlucky for some',
  14: 'Valentine’s day',
  15: 'Young and keen',
  16: 'Sweet sixteen',
  17: 'Dancing queen',
  18: 'Coming of age',
  19: 'Goodbye teens',
  20: 'One score',
  21: 'Key of the door',
  22: 'Two little ducks',
  23: 'Thee and me',
  24: 'Two dozen',
  25: 'Duck and dive',
  26: 'Half a crown',
  27: 'Gateway to heaven',
  28: 'Over weight',
  29: 'Rise and shine',
  30: 'Dirty Gertie',
  31: 'Get up and run',
  32: 'Buckle my shoe',
  33: 'All the threes',
  34: 'Ask for more',
  35: 'Jump and jive',
  36: 'Three dozen',
  37: 'More than eleven',
  38: 'Christmas cake',
  39: 'Steps',
  40: 'Life begins',
  41: 'Time for fun',
  42: 'Winnie the Pooh',
  43: 'Down on your knees',
  44: 'Droopy drawers',
  45: 'Halfway there',
  46: 'Up to tricks',
  47: 'Four and seven',
  48: 'Four dozen',
  49: 'PC',
  50: 'Half a century',
  51: 'Tweak of the thumb',
  52: 'Danny La Rue',
  53: 'Stuck in the tree',
  54: 'Clean the floor',
  55: 'Snakes alive',
  56: 'Shotts bus',
  57: 'Heinz varieties',
  58: 'Make them wait',
  59: 'Brighton line',
  60: 'Five dozen',
  61: 'Baker’s bun',
  62: 'Tickety-boo',
  63: 'Tickle me',
  64: 'Almost retired',
  65: 'Retirement age',
  66: 'Clickety click',
  67: 'Stairway to heaven',
  68: 'Saving grace',
  69: 'Either way up',
  70: 'Three score and ten',
  71: 'Bang on the drum',
  72: 'Six dozen',
  73: 'Queen bee',
  74: 'Hit the floor',
  75: 'Top of the shop',
};

export function callFor(ball: number | null): string {
  if (ball === null) return 'Eyes down';
  return CALLS[ball] ?? `Number ${ball}`;
}
